name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image version latest
        if: github.ref == 'refs/heads/main'
        run: echo "VERSION=latest" >> ${GITHUB_ENV}
      - name: Set image version for PRs to branch name
        if: github.event_name == 'pull_request'
        run: echo "VERSION=${GITHUB_HEAD_REF//\//-}" >> ${GITHUB_ENV}
      - name: Set image version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> ${GITHUB_ENV}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 'ghcr.io/${{ env.IMAGE }}:${{ env.VERSION }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build changelog from PRs with labels
        if: startsWith(github.ref, 'refs/tags/v')
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ".github/changelog-configuration.json"
          # PreReleases still get a changelog, but the next full release gets a diff since the last full release,
          # combining possible changelogs of all previous PreReleases in between.
          # PreReleases show a partial changelog since last PreRelease.
          ignorePreReleases: "${{ !contains(github.ref, '-rc') }}"
          outputFile: .github/release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Read release message from tag commit
        id: tag_message
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git fetch origin +refs/tags/*:refs/tags/*
          # Extract tag message
          TAG_MSG=$(git tag -n --format='%(contents:body)' ${GITHUB_REF##refs/tags/} | tr -d '\r')
          # Join multiple lines belonging to the same paragraph for GitHub
          # markdown.
          # Paragraph breaks should be '\n\n'. List items should be '\n*'. We
          # replace single line breaks which don't preceed a '*' with a space
          # with sed. Note `sed -z` operates on the whole input instead of
          # line-wise. Note that this currently still breaks markdown code
          # blocks.
          TAG_MSG=$(echo "$TAG_MSG" | sed -z 's/\([^\n]\)\n\([^\n\*]\)/\1 \2/g')
          # Set action output `messsage` as JSON-encoded string to preserve
          # newlines. We decode with `fromJSON()` below.
          TAG_MSG=$(jq -n --arg msg "${TAG_MSG}" '$msg')
          echo "message=${TAG_MSG}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          body: "# Summary\n\n${{fromJSON(steps.tag_message.outputs.message)}}\n\n# Changes\n\n${{steps.build_changelog.outputs.changelog}}"
          prerelease: "${{ contains(github.ref, '-rc') }}"
          # Ensure target branch for release is "main"
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete untagged container images
        # We always delete all untagged container images after building an
        # image. This way, there should never be stale untagged images laying
        # around in the registry. In combination with the workflow that
        # deletes PR tags after the PR is closed we should be able to keep the
        # container image registry size in check.
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ github.event.repository.name }}
          validate: true
